# Generated by Django 3.2.4 on 2021-06-18 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import login_code.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=login_code.models.get_code, max_length=4)),
                ('valid_till', models.DateTimeField(default=login_code.models.one_hour_later)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
