# Generated by Django 3.2.4 on 2021-11-19 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
