# Generated by Django 3.2.4 on 2021-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('login_code', '0002_throttlelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throttlelog',
            name='user',
        ),
        migrations.AddField(
            model_name='throttlelog',
            name='key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
