# Generated by Django 4.0.5 on 2022-06-16 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0004_opportunitycategory_organizerrolecategory_and_more'),
        ('bis', '0016_remove_location_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('on_web_start', models.DateField()),
                ('on_web_end', models.DateField()),
                ('introduction', tinymce.models.HTMLField(help_text='Krátce vysvětli význam činnosti a její přínos, aby přilákala zájemce')),
                ('description', tinymce.models.HTMLField(help_text='Přibliž konkrétní činnosti a aktivity, které budou součástí příležitosti')),
                ('location_benefits', tinymce.models.HTMLField(blank=True, help_text='Popiš dopad a přínos činnosti pro dané místě (nezobrazí se u typu spolupráce)')),
                ('personal_benefits', tinymce.models.HTMLField()),
                ('requirements', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='opportunity_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='categories.opportunitycategory')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='bis.location')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OfferedHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_organizer_role', models.CharField(max_length=63)),
                ('additional_team_role', models.CharField(max_length=63)),
                ('info', models.TextField()),
                ('organizer_roles', models.ManyToManyField(related_name='offered_help', to='categories.organizerrolecategory')),
                ('programs', models.ManyToManyField(related_name='offered_help', to='categories.eventprogramcategory')),
                ('team_roles', models.ManyToManyField(related_name='offered_help', to='categories.teamrolecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
