# Generated by Django 3.2.16 on 2022-12-31 11:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='requirements',
            field=tinymce.models.HTMLField(blank=True, help_text='Napiš dovednosti, zkušenosti či vybavení potřebné k zapojení do příležitosti'),
        ),
    ]
