# Generated by Django 3.2.14 on 2022-07-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_opportunitycategory_organizerrolecategory_and_more'),
        ('opportunities', '0002_alter_opportunity_personal_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredhelp',
            name='additional_organizer_role',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='offeredhelp',
            name='additional_team_role',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='offeredhelp',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offeredhelp',
            name='organizer_roles',
            field=models.ManyToManyField(blank=True, related_name='offered_help', to='categories.OrganizerRoleCategory'),
        ),
        migrations.AlterField(
            model_name='offeredhelp',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='offered_help', to='categories.EventProgramCategory'),
        ),
        migrations.AlterField(
            model_name='offeredhelp',
            name='team_roles',
            field=models.ManyToManyField(blank=True, related_name='offered_help', to='categories.TeamRoleCategory'),
        ),
    ]
