# Generated by Django 3.2.14 on 2022-07-27 05:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_auto_20220716_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact_name',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
