# Generated by Django 3.2.14 on 2022-07-27 05:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_auto_20220727_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Nechte prázdné pokud chcete použít e-mail kontaktní osoby', max_length=254),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Nechte prázdné pokud chcete použít jméno kontaktní osoby', max_length=63),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Nechte prázdné pokud chcete použít telefon kontaktní osoby', max_length=128, region=None),
        ),
    ]
