# Generated by Django 3.2.15 on 2022-08-11 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0009_alter_healthinsurancecompany_name'),
        ('bis', '0034_auto_20220811_1729'),
        ('opportunities', '0005_auto_20220727_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='categories.opportunitycategory'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='bis.location'),
        ),
    ]
