# Generated by Django 3.2.15 on 2022-08-13 15:53

import common.thumbnails
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_auto_20220811_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=common.thumbnails.ThumbnailImageField(upload_to='opportunity_images'),
        ),
    ]
