# Generated by Django 3.2.16 on 2022-11-23 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('regions', '0001_initial'),
        ('administration_units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='audit_committee',
            field=models.ManyToManyField(blank=True, help_text='Vidí vše, nemohou editovat', related_name='_administration_units_brontosaurusmovement_audit_committee_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='bis_administrators',
            field=models.ManyToManyField(blank=True, help_text='Mají veškeré oprávnění', related_name='_administration_units_brontosaurusmovement_bis_administrators_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='director',
            field=models.ForeignKey(help_text='Má veškerá oprávnění', on_delete=django.db.models.deletion.PROTECT, related_name='director_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='education_members',
            field=models.ManyToManyField(blank=True, help_text='Vidí pouze uživatele a mohou je editovat pouze kvalifikaci', related_name='_administration_units_brontosaurusmovement_education_members_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='executive_committee',
            field=models.ManyToManyField(blank=True, help_text='Vidí vše, nemohou editovat', related_name='_administration_units_brontosaurusmovement_executive_committee_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='finance_director',
            field=models.ForeignKey(help_text='Má veškerá oprávnění', on_delete=django.db.models.deletion.PROTECT, related_name='finance_director_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='office_workers',
            field=models.ManyToManyField(blank=True, help_text='Mohou měnit vše kromě základních oprávnění', related_name='_administration_units_brontosaurusmovement_office_workers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrationunitcontactaddress',
            name='administration_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_address', to='administration_units.administrationunit'),
        ),
        migrations.AddField(
            model_name='administrationunitcontactaddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region'),
        ),
        migrations.AddField(
            model_name='administrationunitaddress',
            name='administration_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='administration_units.administrationunit'),
        ),
        migrations.AddField(
            model_name='administrationunitaddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region'),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='board_members',
            field=models.ManyToManyField(blank=True, related_name='administration_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_units', to='categories.administrationunitcategory'),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chairman_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='vice_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vice_chairman_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
