# Generated by Django 4.0.4 on 2022-05-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministrationUnitMember',
        ),
    ]
