# Generated by Django 3.2.16 on 2022-11-27 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_units', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
