# Generated by Django 4.0.3 on 2022-05-09 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_units', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationunit',
            name='abbreviation',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='existed_since',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='existed_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='is_for_kids',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='www',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdministrationUnitAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=127)),
                ('city', models.CharField(max_length=63)),
                ('zip_code', models.CharField(max_length=5)),
                ('administration_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='administration_units.administrationunit')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
