# Generated by Django 4.0.3 on 2022-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0003_administrationunit_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunit',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
