# Generated by Django 4.0.3 on 2022-03-11 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0003_alter_event_administrative_unit_and_more'),
        ('administration_units', '0003_brontosaurusmovement_organizingunit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministrativeUnit',
        ),
        migrations.AddField(
            model_name='organizingunit',
            name='board_members',
            field=models.ManyToManyField(related_name='organizing_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='audit_committee',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='bis_administrators',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='director',
            field=models.ForeignKey(help_text='Má veškerá oprávnění', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='education_members',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='executive_committee',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='office_workers',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
