# Generated by Django 4.0.3 on 2022-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0004_alter_administrationunit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationunit',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='ic',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
