# Generated by Django 4.0.4 on 2022-06-01 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_units', '0005_alter_administrationunit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunit',
            name='chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chairman_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brontosaurusmovement',
            name='director',
            field=models.ForeignKey(help_text='Má veškerá oprávnění', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
