# Generated by Django 4.0.3 on 2022-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0005_administrationunit_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunit',
            name='ic',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
