# Generated by Django 4.0.3 on 2022-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0006_alter_administrationunit_ic'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationunit',
            name='import_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
