# Generated by Django 4.0.4 on 2022-06-11 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_units', '0006_alter_administrationunit_chairman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brontosaurusmovement',
            name='finance_director',
            field=models.ForeignKey(default=1622, help_text='Má veškerá oprávnění', on_delete=django.db.models.deletion.CASCADE, related_name='finance_director_of', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brontosaurusmovement',
            name='audit_committee',
            field=models.ManyToManyField(blank=True, help_text='Vidí vše, nemohou editovat', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brontosaurusmovement',
            name='bis_administrators',
            field=models.ManyToManyField(blank=True, help_text='Mají veškeré oprávnění', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brontosaurusmovement',
            name='director',
            field=models.ForeignKey(default=1622, help_text='Má veškerá oprávnění', on_delete=django.db.models.deletion.CASCADE, related_name='director_of', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brontosaurusmovement',
            name='education_members',
            field=models.ManyToManyField(blank=True, help_text='Vidí pouze uživatele a mohou je editovat pouze kvalifikaci', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brontosaurusmovement',
            name='executive_committee',
            field=models.ManyToManyField(blank=True, help_text='Vidí vše, nemohou editovat', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brontosaurusmovement',
            name='office_workers',
            field=models.ManyToManyField(blank=True, help_text='Mohou měnit vše kromě základních oprávnění', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
