# Generated by Django 4.0.5 on 2022-06-11 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_units', '0007_brontosaurusmovement_finance_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationunit',
            name='vice_chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_chairman_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
