# Generated by Django 4.0.3 on 2022-05-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0007_administrationunit_import_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrationunit',
            name='import_id',
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='_import_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
