# Generated by Django 3.2.14 on 2022-07-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('administration_units', '0011_auto_20220718_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunitaddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='regions.region'),
        ),
        migrations.AlterField(
            model_name='administrationunitcontactaddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='regions.region'),
        ),
    ]
