# Generated by Django 3.2.14 on 2022-07-30 07:51

from django.db import migrations

def migrate(apps, schema):
    AdministrationUnit = apps.get_model('administration_units', 'AdministrationUnit')
    for item in AdministrationUnit.objects.all():
        item.phone = item.phone or ''
        item.email = item.email or ''
        item.www = item.www or ''
        item.ic = item.ic or ''
        item.bank_account_number = item.bank_account_number or ''
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0012_auto_20220726_1206'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
