# Generated by Django 3.2.14 on 2022-07-30 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_units', '0013_auto_20220730_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunit',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='ic',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='vice_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_chairman_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='www',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
