# Generated by Django 3.2.14 on 2022-07-30 08:23

from django.db import migrations

def migrate(apps, schema):
    AdministrationUnit = apps.get_model('administration_units', 'AdministrationUnit')

    for au in AdministrationUnit.objects.order_by('-id'):
        query = AdministrationUnit.objects.exclude(id=au.id).filter(abbreviation=au.abbreviation)
        if query.count():
            query.update(abbreviation=au.name)


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0014_auto_20220730_0953'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
