# Generated by Django 3.2.14 on 2022-07-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0015_auto_20220730_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunit',
            name='abbreviation',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='administrationunit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
