# Generated by Django 3.2.14 on 2022-08-10 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration_units', '0016_auto_20220730_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationunit',
            name='board_members',
            field=models.ManyToManyField(blank=True, related_name='administration_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
