# Generated by Django 3.2.15 on 2022-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0019_administrationunit_custom_statues'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationunit',
            name='data_box',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
