# Generated by Django 3.2.15 on 2022-10-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0020_administrationunit_data_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationunit',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='administrationunit',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
