# Generated by Django 3.2.15 on 2022-10-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0021_auto_20221023_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=63)),
                ('administration_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_meetings', to='administration_units.administrationunit')),
            ],
        ),
    ]
