# Generated by Django 3.2.15 on 2022-10-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0022_generalmeeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalmeeting',
            options={'ordering': ('date',)},
        ),
    ]
