# Generated by Django 4.0.3 on 2022-03-23 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPropagation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shown_on_web', models.BooleanField()),
                ('vip_propagation', models.BooleanField(default=False)),
                ('minimum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField()),
                ('invitation_text_introduction', models.TextField()),
                ('invitation_text_practical_information', models.TextField()),
                ('invitation_text_work_description', models.TextField()),
                ('invitation_text_about_us', models.TextField(blank=True)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_where_was_as_contact_person', to=settings.AUTH_USER_MODEL)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.dietcategory')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propagation', to='bis.event')),
                ('intended_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.propagationintendedforcategory')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_required', models.BooleanField(default=True)),
                ('is_event_full', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='bis.event')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_worked', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_on_work_done', models.TextField(blank=True)),
                ('has_attendance_list', models.BooleanField(default=True)),
                ('number_of_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_participants_under_26', models.PositiveIntegerField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='bis.event')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_in_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventPropagationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='event_propagation_images')),
                ('propagation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagation_images', to='event.eventpropagation')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='event_photos')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.eventrecord')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('total_event_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.FileField(blank=True, upload_to='budgets')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.financecategory')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='bis.event')),
                ('grant_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.grantcategory')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
