# Generated by Django 3.2.16 on 2022-11-23 06:45

import common.thumbnails
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('bis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(blank=True, help_text='Pro zaslání dotací', max_length=63)),
                ('grant_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('total_event_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.FileField(blank=True, upload_to='budgets')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='bis.event')),
                ('grant_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.grantcategory')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventPropagation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shown_on_web', models.BooleanField()),
                ('minimum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.CharField(help_text='Max. 12 znaků, "Kč" je doplněno automaticky, nechte prázdné pokud je akce bez poplatku', max_length=12)),
                ('accommodation', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.PositiveSmallIntegerField(blank=True, help_text='Pouze pro dobrovolnické akce', null=True)),
                ('working_days', models.PositiveSmallIntegerField(blank=True, help_text='Pouze pro vícedenní dobrovolnické akce', null=True)),
                ('organizers', models.CharField(max_length=255)),
                ('web_url', models.URLField(blank=True)),
                ('_contact_url', models.URLField(blank=True)),
                ('invitation_text_introduction', tinymce.models.HTMLField()),
                ('invitation_text_practical_information', tinymce.models.HTMLField()),
                ('invitation_text_work_description', tinymce.models.HTMLField(blank=True)),
                ('invitation_text_about_us', tinymce.models.HTMLField(blank=True)),
                ('contact_name', models.CharField(blank=True, help_text='Nechte prázdné pokud chcete použít jméno kontaktní osoby', max_length=63)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Nechte prázdné pokud chcete použít telefon kontaktní osoby', max_length=128, region=None)),
                ('contact_email', models.EmailField(blank=True, help_text='Nechte prázdné pokud chcete použít e-mail kontaktní osoby', max_length=254)),
                ('contact_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_where_was_as_contact_person', to=settings.AUTH_USER_MODEL)),
                ('diets', models.ManyToManyField(blank=True, related_name='events', to='categories.DietCategory')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propagation', to='bis.event')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VIPEventPropagation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_of_event', models.TextField(help_text='Jaké je hlavní téma vaší akce? Jaké jsou hlavní cíle akce? Co nejvýstižněji popište, co akce přináší účastníkům, co zajímavého si zkusí, co se dozví, naučí, v čem se rozvinou...')),
                ('program', models.TextField(help_text='V základu uveďte, jak bude vaše akce programově a dramaturgicky koncipována (motivační příběh, zaměření programu – hry, diskuse, řemesla,...). Uveďte, jak náplň a program akce reflektují potřeby vaší cílové skupiny prvoúčastníků.')),
                ('short_invitation_text', models.TextField(help_text='Ve 2-4 větách nalákejte na vaši akci a zdůrazněte osobní přínos pro účastníky (max. 200 znaků).', max_length=200)),
                ('rover_propagation', models.BooleanField(default=False, help_text='Placená propagace vaší vícedenní akce v časopisu Roverský kmen za poplatek 100 Kč.')),
                ('event_propagation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_propagation', to='event.eventpropagation')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_required', models.BooleanField(default=True)),
                ('is_event_full', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='bis.event')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_worked', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_on_work_done', models.TextField(blank=True)),
                ('attendance_list', models.ImageField(blank=True, null=True, upload_to='attendance_lists')),
                ('number_of_participants', models.PositiveIntegerField(blank=True, help_text='Vyplň pouze pokud nejsou vyplnění konkrétní účastníci', null=True)),
                ('number_of_participants_under_26', models.PositiveIntegerField(blank=True, help_text='Vyplň pouze pokud nejsou vyplnění konkrétní účastníci', null=True)),
                ('note', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='bis.event')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_in_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-event__start',),
            },
        ),
        migrations.CreateModel(
            name='EventPropagationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('image', common.thumbnails.ThumbnailImageField(max_length=200, upload_to='event_propagation_images')),
                ('propagation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.eventpropagation')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', common.thumbnails.ThumbnailImageField(upload_to='event_photos')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.eventrecord')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventFinanceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(upload_to='receipts')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='event.eventfinance')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
