# Generated by Django 3.2.16 on 2022-12-22 22:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='event.eventrecord')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
