# Generated by Django 4.0.4 on 2022-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipeventpropagation',
            name='goals_of_event',
            field=models.TextField(help_text='Jaké je hlavní téma vaší akce? Jaké jsou hlavní cíle akce? Co nejvýstižněji popište, co akce přináší účastníkům, co zajímavého si zkusí, co se dozví, naučí, v čem se rozvinou...'),
        ),
        migrations.AlterField(
            model_name='vipeventpropagation',
            name='program',
            field=models.TextField(help_text='V základu uveďte, jak bude vaše akce programově a dramaturgicky koncipována (motivační příběh, zaměření programu – hry, diskuse, řemesla,...). Uveďte, jak náplň a program akce reflektují potřeby vaší cílové skupiny prvoúčastníků.'),
        ),
        migrations.AlterField(
            model_name='vipeventpropagation',
            name='rover_propagation',
            field=models.BooleanField(default=False, help_text='Placená propagace vaší vícedenní akce v časopisu Roverský kmen za poplatek 100 Kč.'),
        ),
        migrations.AlterField(
            model_name='vipeventpropagation',
            name='short_invitation_text',
            field=models.TextField(help_text='Ve 2-4 větách nalákejte na vaši akci a zdůrazněte osobní přínos pro účastníky (max. 200 znaků).', max_length=200),
        ),
    ]
