# Generated by Django 4.0.3 on 2022-05-12 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfinance',
            old_name='grant_source',
            new_name='grant_category',
        ),
        migrations.RemoveField(
            model_name='eventfinance',
            name='category',
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='_contact_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='accommodation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='organizers',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='rover_propagation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='web_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventpropagation',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_where_was_as_contact_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
