# Generated by Django 4.0.3 on 2022-03-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0003_alter_answer_options'),
        ('categories', '0007_create_qualifications'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='event',
            name='comment_on_work_done',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='event',
            name='finance_category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grant_amount',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grant_source',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_attendance_list',
        ),
        migrations.RemoveField(
            model_name='event',
            name='intended_for',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_text_about_us',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_text_introduction',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_text_practical_information',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_text_work_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_event_full',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_registration_required',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_shown_on_web',
        ),
        migrations.RemoveField(
            model_name='event',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='number_of_participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='number_of_participants_under_26',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_event_cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_hours_worked',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vip_propagation',
        ),
        migrations.RemoveField(
            model_name='eventphoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpropagationimage',
            name='event',
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_required', models.BooleanField(default=True)),
                ('is_event_full', models.BooleanField(default=False)),
                ('questionnaire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='questionnaire.questionnaire')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_worked', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_on_work_done', models.TextField(blank=True)),
                ('has_attendance_list', models.BooleanField(default=True)),
                ('number_of_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_participants_under_26', models.PositiveIntegerField(blank=True, null=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_in_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventPropagation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shown_on_web', models.BooleanField()),
                ('vip_propagation', models.BooleanField(default=False)),
                ('minimum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField()),
                ('invitation_text_introduction', models.TextField()),
                ('invitation_text_practical_information', models.TextField()),
                ('invitation_text_work_description', models.TextField()),
                ('invitation_text_about_us', models.TextField(blank=True)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.dietcategory')),
                ('intended_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.propagationintendedforcategory')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('total_event_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.FileField(blank=True, upload_to='budgets')),
                ('finance_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.financecategory')),
                ('grant_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.grantcategory')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='finance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='event.eventfinance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='propagation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='event.eventpropagation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='event.eventrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='event', to='event.eventregistration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event.eventrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpropagationimage',
            name='propagation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='propagation_images', to='event.eventpropagation'),
            preserve_default=False,
        ),
    ]
