# Generated by Django 4.0.3 on 2022-05-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_grant_source_eventfinance_grant_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpropagation',
            name='rover_propagation',
        ),
        migrations.RemoveField(
            model_name='eventpropagation',
            name='vip_propagation',
        ),
        migrations.CreateModel(
            name='VIPEventPropagation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_of_event', models.TextField()),
                ('program', models.TextField()),
                ('short_invitation_text', models.TextField(max_length=200)),
                ('rover_propagation', models.BooleanField(default=False)),
                ('working_hours', models.PositiveSmallIntegerField()),
                ('working_days', models.PositiveSmallIntegerField()),
                ('event_propagation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_propagation', to='event.eventpropagation')),
            ],
        ),
    ]
