# Generated by Django 4.0.3 on 2022-03-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='event.eventfinance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='propagation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='event.eventpropagation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='event.eventrecord'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='event.eventregistration'),
        ),
    ]
