# Generated by Django 3.2.16 on 2022-12-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontact',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='event.eventrecord'),
        ),
    ]
