# Generated by Django 4.0.3 on 2022-03-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_finance_alter_event_propagation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='finance',
        ),
        migrations.AddField(
            model_name='eventfinance',
            name='event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='finance', to='event.event'),
            preserve_default=False,
        ),
    ]
