# Generated by Django 3.2.16 on 2022-12-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventcontact_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='alternative_registration_link',
            field=models.URLField(blank=True),
        ),
    ]
