# Generated by Django 4.0.4 on 2022-05-31 14:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventpropagation_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpropagation',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Nechte prázdné pokud chcete použít telefon kontaktní osoby', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='eventpropagationimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to='event_propagation_images'),
        ),
    ]
