# Generated by Django 4.0.5 on 2022-06-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_eventpropagation_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpropagationimage',
            name='propagation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.eventpropagation'),
        ),
    ]
