# Generated by Django 4.0.3 on 2022-03-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_finance_eventfinance_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='propagation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='record',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration',
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='propagation', to='event.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='record', to='event.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='event.event'),
            preserve_default=False,
        ),
    ]
