# Generated by Django 4.0.3 on 2022-03-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_propagation_remove_event_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinance',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventpropagation',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propagation', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='event.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='event.event'),
        ),
    ]
