# Generated by Django 4.0.5 on 2022-06-12 09:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventpropagationimage_propagation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpropagation',
            name='invitation_text_introduction',
            field=tinymce.models.HTMLField(),
        ),
    ]
