# Generated by Django 4.0.3 on 2022-03-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventfinance_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='questionnaire',
        ),
    ]
