# Generated by Django 3.2.14 on 2022-07-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_eventpropagation_invitation_text_about_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpropagation',
            name='discounted_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
