# Generated by Django 4.0.3 on 2022-03-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0015_event'),
        ('event', '0007_remove_eventregistration_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinance',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='bis.event'),
        ),
        migrations.AlterField(
            model_name='eventpropagation',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propagation', to='bis.event'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='bis.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='bis.event'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
