# Generated by Django 3.2.14 on 2022-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventpropagation_discounted_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='has_attendance_list',
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='attendance_list',
            field=models.FileField(blank=True, null=True, upload_to='attendance_lists'),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='is_attendance_list_required',
            field=models.BooleanField(default=False),
        ),
    ]
