# Generated by Django 4.0.3 on 2022-03-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventfinance_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfinance',
            old_name='finance_category',
            new_name='category',
        ),
    ]
