# Generated by Django 3.2.14 on 2022-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20220725_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='attendance_list',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_lists'),
        ),
    ]
