# Generated by Django 3.2.14 on 2022-07-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_eventrecord_attendance_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='is_attendance_list_required',
        ),
    ]
