# Generated by Django 3.2.14 on 2022-07-26 08:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_locationaccessibility_locationprogram'),
        ('event', '0011_remove_eventrecord_is_attendance_list_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpropagation',
            name='diet',
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='diets',
            field=models.ManyToManyField(related_name='events', to='categories.DietCategory'),
        ),
        migrations.AlterField(
            model_name='eventpropagation',
            name='invitation_text_work_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
