# Generated by Django 3.2.14 on 2022-07-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20220726_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='number_of_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Vyplň pouze pokud nejsou vyplnění konkrétní účastníci', null=True),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='number_of_participants_under_26',
            field=models.PositiveIntegerField(blank=True, help_text='Vyplň pouze pokud nejsou vyplnění konkrétní účastníci', null=True),
        ),
    ]
