# Generated by Django 3.2.14 on 2022-07-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20220726_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrecord',
            options={'ordering': ('-event__start',)},
        ),
    ]
