# Generated by Django 3.2.14 on 2022-07-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_eventrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfinance',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.CreateModel(
            name='EventFinanceReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(upload_to='receipts')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='event.eventfinance')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
