# Generated by Django 3.2.14 on 2022-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20220730_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventFinanceReceipts',
            new_name='EventFinanceReceipt',
        ),
        migrations.AlterField(
            model_name='eventfinance',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Pro zaslání dotací', max_length=63),
        ),
    ]
