# Generated by Django 3.2.15 on 2022-08-11 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_healthinsurancecompany_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0017_auto_20220730_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfinance',
            name='grant_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.grantcategory'),
        ),
        migrations.AlterField(
            model_name='eventpropagation',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_where_was_as_contact_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventpropagation',
            name='intended_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.propagationintendedforcategory'),
        ),
    ]
