# Generated by Django 3.2.15 on 2022-08-13 15:53

import common.thumbnails
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20220811_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='photo',
            field=common.thumbnails.ThumbnailImageField(upload_to='event_photos'),
        ),
        migrations.AlterField(
            model_name='eventpropagationimage',
            name='image',
            field=common.thumbnails.ThumbnailImageField(max_length=200, upload_to='event_propagation_images'),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='attendance_list',
            field=common.thumbnails.ThumbnailImageField(blank=True, null=True, upload_to='attendance_lists'),
        ),
    ]
