# Generated by Django 3.2.15 on 2022-09-20 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_eventgroupcategory'),
        ('regions', '0002_alter_zipcode_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0019_auto_20220813_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('nickname', models.CharField(blank=True, max_length=63)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('health_issues', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('event_registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='event.eventregistration')),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='categories.sexcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventApplicationClosePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='close_person', to='event.eventapplication')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventApplicationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=127)),
                ('city', models.CharField(max_length=63)),
                ('zip_code', models.CharField(max_length=5)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='event.eventapplication')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
