# Generated by Django 3.2.15 on 2022-09-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_eventapplication_eventapplicationaddress_eventapplicationcloseperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='event_registration',
        ),
        migrations.RemoveField(
            model_name='eventapplication',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='eventapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eventapplicationaddress',
            name='application',
        ),
        migrations.RemoveField(
            model_name='eventapplicationaddress',
            name='region',
        ),
        migrations.RemoveField(
            model_name='eventapplicationcloseperson',
            name='application',
        ),
    ]
