# Generated by Django 3.2.15 on 2022-09-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20220920_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='working_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pouze pro vícedenní dobrovolnické akce', null=True),
        ),
        migrations.AddField(
            model_name='eventpropagation',
            name='working_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pouze pro dobrovolnické akce', null=True),
        ),
    ]
