# Generated by Django 3.2.15 on 2022-09-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_eventgroupcategory'),
        ('event', '0023_auto_20220926_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpropagation',
            name='intended_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propagations', to='categories.propagationintendedforcategory'),
        ),
    ]
