# Generated by Django 3.2.15 on 2022-09-27 10:16

from django.db import migrations

from bis.helpers import print_progress


def migrate(apps, schema):
    Event = apps.get_model('bis', 'Event')
    events = list(Event.objects.all())
    for i, event in enumerate(events):
        print_progress('copy intended for', i, len(events))
        if hasattr(event, 'propagation'):
            event.intended_for = event.propagation.intended_for
            event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0024_alter_eventpropagation_intended_for'),
    ]

    operations = [
        migrations.RunPython(migrate),
        migrations.RemoveField(
            model_name='eventpropagation',
            name='intended_for',
        ),
    ]
