# Generated by Django 3.2.15 on 2022-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_remove_eventpropagation_intended_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpropagation',
            name='discounted_cost',
        ),
        migrations.AlterField(
            model_name='eventpropagation',
            name='cost',
            field=models.CharField(help_text='Max. 12 znaků, "Kč" je doplněno automaticky, nechte prázdné pokud je akce bez poplatku', max_length=12),
        ),
    ]
