# Generated by Django 3.2.15 on 2022-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_auto_20221002_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='attendance_list',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_lists'),
        ),
    ]
