# Generated by Django 3.2.15 on 2022-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_eventdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
