# Generated by Django 3.2.15 on 2022-11-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_eventrecord_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpropagation',
            name='accommodation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
