# Generated by Django 4.0.3 on 2022-03-11 16:20
from django.contrib.gis.geos import Point
from django.db import migrations


def migrate(apps, _):
    User = apps.get_model('bis', 'User')
    user = User(
        email='admin@lomic.cz',
        password='pbkdf2_sha256$260000$5A51hlxtJWGWjeUa2SVfOw$bw+2w23PvZU4oNEjY5+UxczXdXRdrpPPIqAoZD1sLcM=',
        is_superuser=True,
    )
    user.save()

    Location = apps.get_model('bis', 'Location')
    plumlov = Location.objects.create(name='Plumlov', gps_location=Point(17.0137164, 49.4645144, srid=4326))
    mnv = Location.objects.create(name='Moravská nová ves', gps_location=Point(17.0269281, 48.7986308, srid=4326))


class Migration(migrations.Migration):
    dependencies = [
        ('bis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
