# Generated by Django 3.2.16 on 2022-11-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(),
        ),
    ]
