# Generated by Django 4.0.3 on 2022-03-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0003_brontosaurusmovement_organizingunit_and_more'),
        ('bis', '0002_some_init_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='administrative_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='administration_units.organizingunit'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='administrative_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='administration_units.organizingunit'),
        ),
    ]
