# Generated by Django 3.2.16 on 2022-11-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0002_auto_20221127_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=1, help_text='Zobrazí se na webu jako místo konání akce', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bis.location'),
            preserve_default=False,
        ),
    ]
