# Generated by Django 4.0.3 on 2022-03-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0002_user_email_exists_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.CharField(max_length=127),
        ),
    ]
