# Generated by Django 4.0.3 on 2022-03-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0003_alter_event_administrative_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='administrative_unit',
            new_name='organizing_unit',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='administrative_unit',
            new_name='organizing_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
