# Generated by Django 4.0.4 on 2022-05-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0003_remove_user_email_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='order',
        ),
    ]
