# Generated by Django 4.0.3 on 2022-03-09 12:05

from django.db import migrations


def migrate(apps, schema_editor):
    User = apps.get_model('bis', 'User')
    user = User(
        email='admin@lomic.cz',
        password='pbkdf2_sha256$260000$5A51hlxtJWGWjeUa2SVfOw$bw+2w23PvZU4oNEjY5+UxczXdXRdrpPPIqAoZD1sLcM=',
        is_superuser=True,
    )
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0003_rename_members_administrativeunit_board_members_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
