# Generated by Django 3.2.16 on 2022-11-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0003_auto_20221130_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_completed',
            new_name='is_complete',
        ),
    ]
