# Generated by Django 4.0.3 on 2022-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0004_qualification_approved_by_qualification_valid_since_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='qualification',
            name='valid_since',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='valid_till',
            field=models.DateField(),
        ),
    ]
