# Generated by Django 4.0.4 on 2022-05-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0004_remove_useremail_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_exists',
        ),
    ]
