# Generated by Django 4.0.3 on 2022-03-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_certificatecategory'),
        ('bis', '0005_alter_user_managers_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='categories.certificatecategory'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
