# Generated by Django 4.0.4 on 2022-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0005_remove_user_email_exists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremail',
            options={'ordering': ('order', '-id')},
        ),
        migrations.AddField(
            model_name='useremail',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
