# Generated by Django 4.0.3 on 2022-03-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_certificatecategory_qualificationcategory'),
        ('bis', '0006_alter_certificate_category_alter_certificate_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificate',
            new_name='Qualification',
        ),
    ]
