# Generated by Django 4.0.3 on 2022-05-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0006_location_location_location_patron_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
