# Generated by Django 3.2.16 on 2022-12-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0006_alter_qualification_valid_till'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_internal',
        ),
    ]
