# Generated by Django 4.0.3 on 2022-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0007_alter_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='import_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='import_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='import_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='import_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
