# Generated by Django 4.0.4 on 2022-05-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0008_alter_event_other_organizers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',)},
        ),
    ]
