# Generated by Django 4.0.3 on 2022-05-12 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_delete_financecategory'),
        ('bis', '0008_location_import_id_membership_import_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='import_id',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='import_id',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='import_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='import_id',
        ),
        migrations.AddField(
            model_name='event',
            name='_import_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.eventcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.eventprogramcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='_import_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='membership',
            name='_import_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='qualification',
            name='_import_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='_import_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bis.location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_where_was_as_main_organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
