# Generated by Django 4.0.3 on 2022-03-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0008_rename_image_eventphoto_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationPhotos',
            new_name='LocationPhoto',
        ),
    ]
