# Generated by Django 4.0.4 on 2022-06-01 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0009_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_duplicates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
