# Generated by Django 4.0.3 on 2022-03-09 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0009_rename_locationphotos_locationphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeunit',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='eventphoto',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='eventpropagationimage',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='locationphoto',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='qualification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
