# Generated by Django 4.0.4 on 2022-06-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0010_duplicateuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DuplicateUser',
        ),
    ]
