# Generated by Django 4.0.3 on 2022-03-10 07:21
from django.contrib.gis.geos import Point
from django.db import migrations
from django.utils import timezone


def migrate(apps, _):
    AdministrativeUnit = apps.get_model('bis', 'AdministrativeUnit')
    Location = apps.get_model('bis', 'Location')
    User = apps.get_model('bis', 'User')
    ustredi = AdministrativeUnit.objects.get_or_create(name='Ústředí')[0]
    orchis = AdministrativeUnit.objects.get_or_create(name='Orchis', parent=ustredi)[0]
    rozruch = AdministrativeUnit.objects.get_or_create(name='Rozruch', parent=ustredi)[0]

    plumlov = Location.objects.create(name='Plumlov', gps_location=Point(17.0137164, 49.4645144, srid=4326))
    mnv = Location.objects.create(name='Moravská nová ves', gps_location=Point(17.0269281, 48.7986308, srid=4326))

    pepa = User.objects.create(
        first_name='Pepa',
        last_name='Kuba',
        nickname='Pepka',
        phone='+420728487630',
        birthday=timezone.datetime(1996, 2, 5),
        email='pepka@lomic.cz',
    )
    john = User.objects.create(
        first_name='John',
        last_name='Nový',
        nickname='Jonny',
        phone='+420728487630',
        birthday=timezone.datetime(1999, 2, 7),
        email='jonny@lomic.cz',
    )
    lehni = User.objects.create(
        first_name='Lenka',
        last_name='Hani',
        nickname='Lehni',
        phone='+420728487630',
        birthday=timezone.datetime(1989, 2, 7),
        email='lehni@lomic.cz',
    )
    veri = User.objects.create(
        first_name='Verča',
        last_name='Stará',
        nickname='Veri',
        phone='+420728487630',
        birthday=timezone.datetime(2020, 5, 12),
        email='veri@lomic.cz',
    )

    PropagationIntendedForCategory = apps.get_model('categories', 'PropagationIntendedForCategory')
    DietCategory = apps.get_model('categories', 'DietCategory')

    DietCategory.objects.create(name='s masem')
    DietCategory.objects.create(name='vegetariánská')
    DietCategory.objects.create(name='veganská')

    PropagationIntendedForCategory.objects.create(name='Pro všechny')
    PropagationIntendedForCategory.objects.create(name='Pro mládež a dospělé')
    PropagationIntendedForCategory.objects.create(name='Pro děti')
    PropagationIntendedForCategory.objects.create(name='Pro rodiče s dětmi')
    PropagationIntendedForCategory.objects.create(name='Pro prvoúčastníky')


def revert(apps, _):
    Location = apps.get_model('bis', 'Location')

    User = apps.get_model('bis', 'User')
    User.objects.filter(nickname__in=['Veri', 'Lehni', 'Jonny', 'Pepka']).delete()

    for model in [Location]:
        model.objects.all().delete()

    apps.get_model('categories', 'FinanceCategory').objects.all().delete()
    apps.get_model('categories', 'GrantCategory').objects.all().delete()
    apps.get_model('categories', 'PropagationIntendedForCategory').objects.all().delete()
    apps.get_model('categories', 'DietCategory').objects.all().delete()
    apps.get_model('categories', 'QualificationCategory').objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('bis', '0011_alter_event_budget_alter_event_grant_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate, revert)
    ]
