# Generated by Django 4.0.5 on 2022-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0012_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_str',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
