# Generated by Django 4.0.3 on 2022-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0012_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maximum_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='minimum_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
