# Generated by Django 4.0.3 on 2022-03-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0013_alter_event_maximum_age_alter_event_minimum_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventphoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpropagationimage',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventPhoto',
        ),
        migrations.DeleteModel(
            name='EventPropagationImage',
        ),
    ]
