# Generated by Django 4.0.5 on 2022-06-13 06:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0014_usercontactaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
