# Generated by Django 4.0.3 on 2022-03-10 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0014_remove_eventphoto_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('is_canceled', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateField()),
                ('is_internal', models.BooleanField(default=False)),
                ('number_of_sub_events', models.PositiveIntegerField(default=1)),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bis.administrativeunit')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bis.location')),
                ('main_organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('other_organizers', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
