# Generated by Django 4.0.3 on 2022-03-10 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0015_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qualification', to=settings.AUTH_USER_MODEL),
        ),
    ]
