# Generated by Django 4.0.5 on 2022-06-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_opportunitycategory_organizerrolecategory_and_more'),
        ('bis', '0016_remove_location_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.eventprogramcategory'),
        ),
    ]
