# Generated by Django 3.2.14 on 2022-07-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0008_administrationunit_vice_chairman'),
        ('bis', '0017_alter_event_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='administration_unit',
        ),
        migrations.AddField(
            model_name='event',
            name='administration_units',
            field=models.ManyToManyField(related_name='events', to='administration_units.AdministrationUnit'),
        ),
    ]
