# Generated by Django 3.2.14 on 2022-07-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_locationaccessibility_locationprogram'),
        ('bis', '0018_auto_20220716_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='accessibility_from_brno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.locationaccessibility'),
        ),
        migrations.AddField(
            model_name='location',
            name='accessibility_from_prague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.locationaccessibility'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations_where_is_contact_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='facilities',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='for_beginners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_unexplored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='options_around',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.locationprogram'),
        ),
        migrations.AddField(
            model_name='location',
            name='volunteering_work',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='volunteering_work_done',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='volunteering_work_goals',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='patron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patron_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
