# Generated by Django 3.2.14 on 2022-07-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0006_alter_region_options'),
        ('bis', '0020_location_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='other.region'),
            preserve_default=False,
        ),
    ]
