# Generated by Django 3.2.14 on 2022-07-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0009_zipcode'),
        ('bis', '0022_alter_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='other.region'),
        ),
        migrations.AddField(
            model_name='usercontactaddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='other.region'),
        ),
    ]
