# Generated by Django 3.2.14 on 2022-07-18 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0023_auto_20220718_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='close_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
