# Generated by Django 3.2.14 on 2022-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0025_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_attendance_list_required',
            field=models.BooleanField(default=False),
        ),
    ]
