# Generated by Django 3.2.14 on 2022-08-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0028_auto_20220730_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bis.location'),
        ),
    ]
