# Generated by Django 3.2.14 on 2022-08-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0029_auto_20220810_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='online_link',
            field=models.URLField(blank=True, help_text='Vyplňte, pokud se událost koná online'),
        ),
    ]
