# Generated by Django 3.2.14 on 2022-08-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_rolecategory'),
        ('bis', '0030_alter_event_online_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_categories',
            field=models.ManyToManyField(related_name='users', to='categories.RoleCategory'),
        ),
    ]
