# Generated by Django 3.2.14 on 2022-08-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0031_user_role_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_categories',
            new_name='roles',
        ),
    ]
