# Generated by Django 3.2.14 on 2022-08-10 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_healthinsurancecompany'),
        ('bis', '0032_rename_role_categories_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health_insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='categories.healthinsurancecompany'),
        ),
        migrations.AddField(
            model_name='user',
            name='health_issues',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='close_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looking_over', to=settings.AUTH_USER_MODEL),
        ),
    ]
