# Generated by Django 3.2.15 on 2022-08-11 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0018_auto_20220811_1729'),
        ('regions', '0002_alter_zipcode_region'),
        ('categories', '0009_alter_healthinsurancecompany_name'),
        ('bis', '0033_auto_20220810_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.eventcategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bis.location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_where_was_as_main_organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.eventprogramcategory'),
        ),
        migrations.AlterField(
            model_name='location',
            name='accessibility_from_brno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='categories.locationaccessibility'),
        ),
        migrations.AlterField(
            model_name='location',
            name='accessibility_from_prague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='categories.locationaccessibility'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_where_is_contact_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='patron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patron_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.locationprogram'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='regions.region'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='administration_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='administration_units.administrationunit'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='categories.membershipcategory'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_qualifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='categories.qualificationcategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='close_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='looking_over', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='health_insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='categories.healthinsurancecompany'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region'),
        ),
        migrations.AlterField(
            model_name='usercontactaddress',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region'),
        ),
    ]
