# Generated by Django 3.2.15 on 2022-08-13 15:53

import common.thumbnails
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_healthinsurancecompany_name'),
        ('bis', '0034_auto_20220811_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='program',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.eventprogramcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationphoto',
            name='photo',
            field=common.thumbnails.ThumbnailImageField(upload_to='location_photos'),
        ),
    ]
