# Generated by Django 3.2.15 on 2022-08-17 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_sexcategory'),
        ('bis', '0035_auto_20220813_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='categories.sexcategory'),
        ),
    ]
