# Generated by Django 3.2.15 on 2022-09-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0037_auto_20220821_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
