# Generated by Django 3.2.15 on 2022-09-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0039_auto_20220913_0935'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique name and birthday',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'last_name', 'birthday')},
        ),
    ]
