# Generated by Django 3.2.15 on 2022-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0042_auto_20220913_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClosePerson',
            new_name='UserClosePerson',
        ),
        migrations.AddConstraint(
            model_name='usercloseperson',
            constraint=models.CheckConstraint(check=models.Q(('phone__length__gt', 0), ('email__length__gt', 0), _connector='OR'), name='phone_or_email'),
        ),
    ]
