# Generated by Django 3.2.15 on 2022-09-14 06:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0043_auto_20220914_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='usercloseperson',
            name='phone_or_email',
        ),
        migrations.RemoveField(
            model_name='location',
            name='contact_person',
        ),
        migrations.AlterField(
            model_name='usercloseperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='usercloseperson',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='locationcontactperson',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='bis.location'),
        ),
    ]
