# Generated by Django 3.2.15 on 2022-09-14 06:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0044_auto_20220914_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patron',
        ),
        migrations.CreateModel(
            name='LocationPatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patron', to='bis.location')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
