# Generated by Django 3.2.15 on 2022-09-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_eventgroupcategory'),
        ('bis', '0045_auto_20220914_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.eventgroupcategory'),
            preserve_default=False,
        ),
    ]
