# Generated by Django 3.2.15 on 2022-09-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0046_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Zobrazí se na webu jako místo konání akce', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bis.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='options_around',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='volunteering_work',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='volunteering_work_done',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='volunteering_work_goals',
            field=models.TextField(blank=True),
        ),
    ]
