# Generated by Django 3.2.15 on 2022-09-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_eventgroupcategory'),
        ('bis', '0047_auto_20220926_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='intended_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='categories.propagationintendedforcategory'),
            preserve_default=False,
        ),
    ]
