# Generated by Django 3.2.15 on 2022-10-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0048_event_intended_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
