# Generated by Django 3.2.15 on 2022-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0052_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
    ]
