# Generated by Django 3.2.15 on 2022-10-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0053_user_internal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_name',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
