# Generated by Django 3.2.16 on 2022-11-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0055_user_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-tmpid',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='tmpid',
        ),
    ]
