# Generated by Django 3.2.16 on 2022-11-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0056_auto_20221123_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        ),
    ]
