# Generated by Django 3.2.16 on 2022-11-23 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0057_rename_uuid_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='tmpid',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
