# Generated by Django 3.2.16 on 2022-11-23 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0058_auto_20221123_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_search_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
    ]
