# Generated by Django 4.0.3 on 2022-03-11 16:18

from django.db import migrations

# Generated by Django 4.0.3 on 2022-03-10 07:21
from django.contrib.gis.geos import Point
from django.db import migrations


def migrate(apps, _):
    PropagationIntendedForCategory = apps.get_model('categories', 'PropagationIntendedForCategory')
    DietCategory = apps.get_model('categories', 'DietCategory')

    DietCategory.objects.create(name='s masem')
    DietCategory.objects.create(name='vegetariánská')
    DietCategory.objects.create(name='veganská')

    PropagationIntendedForCategory.objects.create(name='Pro všechny')
    PropagationIntendedForCategory.objects.create(name='Pro mládež a dospělé')
    PropagationIntendedForCategory.objects.create(name='Pro děti')
    PropagationIntendedForCategory.objects.create(name='Pro rodiče s dětmi')
    PropagationIntendedForCategory.objects.create(name='Pro prvoúčastníky')

    QualificationCategory = apps.get_model('categories', 'QualificationCategory')
    c = QualificationCategory.objects.create(
        name='Konzultant',
        description='nejvyšší kvalifikace',
        parent=None,
    )
    i = QualificationCategory.objects.create(
        name='Instruktor',
        description='OHB + ODHB',
        parent=c,
    )
    odhb = QualificationCategory.objects.create(
        name='ODHB',
        description='Organizátor dětských akcí HB',
        parent=i,
    )
    QualificationCategory.objects.create(
        name='OpDHB',
        description='Praktikant dětských akcí HB',
        parent=odhb,
    )
    ohb = QualificationCategory.objects.create(
        name='OHB',
        description='Organizátor akcí HB',
        parent=i,
    )
    QualificationCategory.objects.create(
        name='OvHB',
        description='Organizátor víkendových akcí HB',
        parent=ohb,
    )


def revert(apps, _):
    apps.get_model('categories', 'FinanceCategory').objects.all().delete()
    apps.get_model('categories', 'GrantCategory').objects.all().delete()
    apps.get_model('categories', 'PropagationIntendedForCategory').objects.all().delete()
    apps.get_model('categories', 'DietCategory').objects.all().delete()
    apps.get_model('categories', 'QualificationCategory').objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate, revert)
    ]
