# Generated by Django 4.0.4 on 2022-05-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdministrationUnitBoardMemberCategory',
        ),
    ]
