# Generated by Django 3.2.16 on 2022-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='qualificationcategory',
            name='parents',
            field=models.ManyToManyField(related_name='included_qualifications', to='categories.QualificationCategory'),
        ),
    ]
