# Generated by Django 4.0.3 on 2022-05-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_grant_source_eventfinance_grant_category_and_more'),
        ('categories', '0002_eventcategory_eventprogramcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceCategory',
        ),
    ]
