# Generated by Django 4.0.3 on 2022-03-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0006_alter_certificate_category_alter_certificate_user'),
        ('categories', '0002_certificatecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertificateCategory',
            new_name='QualificationCategory',
        ),
    ]
