# Generated by Django 4.0.3 on 2022-03-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_certificatecategory_qualificationcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietcategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='financecategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='grantcategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='propagationintendedforcategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='qualificationcategory',
            options={'ordering': ('id',)},
        ),
    ]
