# Generated by Django 4.0.3 on 2022-03-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_dietcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='included_qualifications', to='categories.qualificationcategory'),
        ),
    ]
