# Generated by Django 4.0.3 on 2022-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_qualificationcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationcategory',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
