# Generated by Django 3.2.14 on 2022-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_locationaccessibility_locationprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsourcecategory',
            name='_import_id',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
