# Generated by Django 4.0.3 on 2022-03-10 09:03

from django.db import migrations


def migrate(apps, _):
    QualificationCategory = apps.get_model('categories', 'QualificationCategory')
    c = QualificationCategory.objects.create(
        name='Konzultant',
        description='nejvyšší kvalifikace',
        parent=None,
    )
    i = QualificationCategory.objects.create(
        name='Instruktor',
        description='OHB + ODHB',
        parent=c,
    )
    odhb = QualificationCategory.objects.create(
        name='ODHB',
        description='Organizátor dětských akcí HB',
        parent=i,
    )
    QualificationCategory.objects.create(
        name='OpDHB',
        description='Praktikant dětských akcí HB',
        parent=odhb,
    )
    ohb = QualificationCategory.objects.create(
        name='OHB',
        description='Organizátor akcí HB',
        parent=i,
    )
    QualificationCategory.objects.create(
        name='OvHB',
        description='Organizátor víkendových akcí HB',
        parent=ohb,
    )


def revert(apps, _):
    QualificationCategory = apps.get_model('categories', 'QualificationCategory')
    QualificationCategory.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0006_qualificationcategory_description'),
    ]

    operations = [
        migrations.RunPython(migrate, revert)
    ]
