# Generated by Django 3.2.14 on 2022-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_healthinsurancecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurancecompany',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
