# Generated by Django 3.2.15 on 2022-08-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0037_auto_20220821_1636'),
        ('categories', '0010_sexcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationAccessibility',
            new_name='LocationAccessibilityCategory',
        ),
        migrations.RenameModel(
            old_name='LocationProgram',
            new_name='LocationProgramCategory',
        ),
    ]
