# Generated by Django 3.2.16 on 2022-11-23 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import donations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('administration_units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to_newsletter', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='na webu a v závěrečné zprávě')),
                ('has_recurrent_donation', models.BooleanField(default=False)),
                ('internal_note', models.TextField(blank=True)),
                ('date_joined', models.DateField(default=donations.models.get_today)),
                ('basic_section_support', models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'basic_section'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_as_basic_section', to='administration_units.administrationunit')),
                ('regional_center_support', models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'regional_center'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_as_regional_center', to='administration_units.administrationunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_joined',),
            },
        ),
        migrations.CreateModel(
            name='UploadBankRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank_records')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VariableSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_symbol', models.PositiveBigIntegerField(unique=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_symbols', to='donations.donor')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_at', models.DateField()),
                ('amount', models.IntegerField()),
                ('_variable_symbol', models.PositiveBigIntegerField(help_text='pro párování na dárce', null=True)),
                ('_import_id', models.PositiveIntegerField(null=True)),
                ('info', models.TextField()),
                ('donation_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='categories.donationsourcecategory')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.donor')),
            ],
            options={
                'ordering': ('-donated_at',),
            },
        ),
    ]
