# Generated by Django 4.0.4 on 2022-06-01 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import donations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration_units', '0006_alter_administrationunit_chairman_and_more'),
        ('categories', '0003_donationsourcecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to_newsletter', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('date_joined', models.DateField()),
                ('basic_section_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supported_as_basic_section', to='administration_units.administrationunit')),
                ('regional_center_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supported_as_regional_center', to='administration_units.administrationunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UploadBankRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bank_records')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VariableSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_symbol', models.PositiveIntegerField(unique=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_symbols', to='donations.donor')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_at', models.DateField()),
                ('amount', models.IntegerField()),
                ('donation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='categories.donationsourcecategory')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donor')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
