# Generated by Django 4.0.4 on 2022-06-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('-donated_at',)},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.AddField(
            model_name='donation',
            name='_variable_symbol',
            field=models.PositiveIntegerField(blank=True, help_text='pro párování na dárce', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='is_public',
            field=models.BooleanField(default=True, help_text='na webu a v závěrečné zprávě'),
        ),
    ]
