# Generated by Django 4.0.4 on 2022-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='_variable_symbol',
            field=models.PositiveBigIntegerField(blank=True, help_text='pro párování na dárce', null=True),
        ),
        migrations.AlterField(
            model_name='variablesymbol',
            name='variable_symbol',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
