# Generated by Django 4.0.5 on 2022-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation__variable_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='_import_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
