# Generated by Django 3.2.14 on 2022-07-30 10:00

import dateutil.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation__import_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='has_recurrent_donation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_joined',
            field=models.DateField(default=dateutil.utils.today),
        ),
    ]
