# Generated by Django 3.2.14 on 2022-07-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20220730_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='_variable_symbol',
            field=models.PositiveBigIntegerField(help_text='pro párování na dárce', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donor'),
        ),
    ]
