# Generated by Django 3.2.14 on 2022-07-30 12:40

from django.db import migrations, models
import donations.models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20220730_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_joined',
            field=models.DateField(default=donations.models.get_today),
        ),
    ]
