# Generated by Django 3.2.15 on 2022-08-11 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import donations.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0018_auto_20220811_1729'),
        ('categories', '0009_alter_healthinsurancecompany_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0007_alter_donor_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='categories.donationsourcecategory'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='basic_section_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_as_basic_section', to='administration_units.administrationunit', validators=[donations.models.is_basic_section]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='regional_center_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_as_regional_center', to='administration_units.administrationunit', validators=[donations.models.is_regional_center]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
    ]
