# Generated by Django 3.2.15 on 2022-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20220811_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
    ]
