# Generated by Django 3.2.15 on 2022-08-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration_units', '0018_auto_20220811_1729'),
        ('donations', '0009_donor_internal_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='basic_section_support',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'basic_section'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_as_basic_section', to='administration_units.administrationunit'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='regional_center_support',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'regional_center'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_as_regional_center', to='administration_units.administrationunit'),
        ),
    ]
