# Generated by Django 4.0.4 on 2022-06-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_uploadbankrecords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadBankRecords',
        ),
    ]
