# Generated by Django 4.0.5 on 2022-06-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0005_auto_20220613_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('id',)},
        ),
    ]
