# Generated by Django 3.2.14 on 2022-07-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0007_auto_20220716_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duplicateuser',
            options={'ordering': ('id',)},
        ),
    ]
