# Generated by Django 3.2.14 on 2022-07-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0027_auto_20220726_1206'),
        ('other', '0009_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
