# Generated by Django 3.2.15 on 2022-09-13 07:40

from django.conf import settings
from django.db import migrations


def migrate(apps, schema):
    DuplicateUser = apps.get_model('other', 'DuplicateUser')
    DuplicateUser.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('other', '0010_auto_20220726_1206'),
    ]

    operations = [
        migrations.RunPython(migrate),
        migrations.AlterUniqueTogether(
            name='duplicateuser',
            unique_together={('user', 'other')},
        ),
    ]
