# Generated by Django 3.2.15 on 2022-10-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_rename_propagationintendedforcategory_eventintendedforcategory'),
        ('other', '0011_alter_duplicateuser_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True)),
                ('for_roles', models.ManyToManyField(related_name='dashboard_items', to='categories.RoleCategory')),
            ],
        ),
    ]
