# Generated by Django 3.2.15 on 2022-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0012_dashboarditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarditem',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='dashboarditem',
            name='repeats_every_year',
            field=models.BooleanField(default=False),
        ),
    ]
