# Generated by Django 3.2.14 on 2022-08-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20220730_1615'),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='event_registration',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='event.eventregistration'),
            preserve_default=False,
        ),
    ]
