# Generated by Django 4.0.3 on 2022-03-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='questionnaireanswers',
            options={'ordering': ('id',)},
        ),
    ]
