# Generated by Django 3.2.15 on 2022-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_questionnaireanswers_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
