# Generated by Django 3.2.15 on 2022-09-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_eventapplication_eventapplicationaddress_eventapplicationcloseperson'),
        ('questionnaire', '0004_questionnaire_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='part_of',
        ),
        migrations.AddField(
            model_name='answer',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='event.eventapplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='after_submit_text',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='QuestionnaireAnswers',
        ),
    ]
