# Generated by Django 3.2.15 on 2022-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20220920_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
